//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SubCategory.java
//  @ Date : 1/21/2012
//  @ Author : Sepehr
//
//

package com.sefryek.doublepizza.model;

import java.io.Serializable;

public class SubCategory implements Serializable {

    private Class type;
    private Object object;

    public SubCategory(){
        
    }

    public SubCategory(Class type,Object item){
        this.type=type;
        this.object=item;
    }

    public Class getType() {
        return type;
    }

    public void setType(Class type) {
        this.type = type;
    }

    public Object getObject() {
        return object;
    }

    public void setObject(Object object) {
        this.object = object;
    }


}