package com.sefryek.doublepizza.model;

import java.io.Serializable;
import java.math.BigDecimal;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BasketItem.java
//  @ Date : 1/12/2012
//  @ Author : 
//
//


public class BasketItem implements Serializable{
    private static Integer basketItemCounter = 0;

    private Integer identifier;
    private Object object;
    private Class classType;


    public BasketItem() {
        this.identifier = basketItemCounter++;
    }

    public Integer getIdentifier() {
        return identifier;
    }

    public void setIdentifier(Integer identifier) {
        this.identifier = identifier;
    }

    public Object getObject() {
        return object;
    }

    public void setObject(Object object) {
        this.object = object;
    }

    public Class getClassType() {
        return classType;
    }

    public void setClassType(Class classType) {
        this.classType = classType;
    }

    public BigDecimal getPrice() {

        BigDecimal price = new BigDecimal(0);

        if (getClassType() == BasketSingleItem.class) {
            BasketSingleItem basketSingleItem = (BasketSingleItem) getObject();
            price = basketSingleItem.getPrice();

        } else { //if (basketItem.getClassType() == BasketCombinedItem.class)
            BasketCombinedItem basketCombinedItem = (BasketCombinedItem) getObject();
            price = basketCombinedItem.getPrice();

        }

        return price;
    }
}
