package com.sefryek.doublepizza.model;

import com.sefryek.doublepizza.InMemoryData;
import com.sefryek.doublepizza.core.helpers.BasketSingleItemHelper;
import com.sefryek.doublepizza.core.helpers.SuggestionsHelper;

import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BasketSingleItem.java
//  @ Date : 1/12/2012
//  @ Author : 
//
//


public class BasketSingleItem {
    private static Integer basketItemIdCounter = 0;

    private Integer identifier; //this class objects are made unique by this property 
    private String id; // refer to modifierId
    private String groupId; // refer to modGroNo;
    private Integer quantity;

    private Map<Integer, String> selectedToppingMap;

    public BasketSingleItem() {
        this.setIdentifier(basketItemIdCounter++);

        this.selectedToppingMap = new HashMap<Integer, String>();
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public Integer getIdentifier() {
        return identifier;
    }

    public void setIdentifier(Integer identifier) {
        this.identifier = identifier;
    }

    public MenuSingleItem getSingle() {
        MenuSingleItem menuSingleItem = InMemoryData.findMenuSingleItemByIdAndGroupId(id, groupId);
        if (menuSingleItem == null)
            menuSingleItem = SuggestionsHelper.findMenuSingleItemFromSuggestionsById(id);

        return menuSingleItem;
    }

    public BigDecimal getPrice() {
        BasketSingleItemHelper helper = new BasketSingleItemHelper();
        return helper.getPrice(this);
    }

    public Map<Integer, String> getSelectedToppingMap() {
        return selectedToppingMap;
    }

    public void setSelectedToppingMap(Map<Integer, String> selectedToppingMap) {
        this.selectedToppingMap = selectedToppingMap;
    }
}
