package com.sefryek.doublepizza.model;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BasketCombinedItem.java
//  @ Date : 1/12/2012
//  @ Author : 
//
//


import com.sefryek.doublepizza.InMemoryData;
import com.sefryek.doublepizza.core.helpers.BasketCombinedItemHelper;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class BasketCombinedItem {

    private static Integer basketItemIdCounter = 0;

    private Integer identifier;
	private String productNoRef;
    private String groupIdRef;


	private List<BasketSingleItem> basketSingleItemList = new ArrayList<BasketSingleItem>();
	private Byte quantity;

    public BasketCombinedItem(){
        this.setIdentifier(basketItemIdCounter++);
        this.basketSingleItemList = new ArrayList<BasketSingleItem>();
    }

    public Integer getIdentifier() {
        return identifier;
    }

    public void setIdentifier(Integer identifier) {
        this.identifier = identifier;
    }

    public List<BasketSingleItem> getBasketSingleItemList() {
        return basketSingleItemList;
    }
    public void setBasketSingleItemList(List<BasketSingleItem> basketSingleItemList) {
        this.basketSingleItemList = basketSingleItemList;
    }

    public Byte getQuantity() {
        return quantity;
    }
    public void setQuantity(Byte quantity) {
        this.quantity = quantity;
    }

    public String getProductNoRef() {
        return productNoRef;
    }

    public void setProductNoRef(String productNoRef) {
        this.productNoRef = productNoRef;
    }

    public String getGroupIdRef() {
        return groupIdRef;
    }

    public void setGroupIdRef(String groupIdRef) {
        this.groupIdRef = groupIdRef;
    }

    public CombinedMenuItem getCombined(){
        return InMemoryData.findCombinedMenuItemByProdNoAndGroupId(productNoRef, groupIdRef);
    }

    public BigDecimal getPrice(){
        BasketCombinedItemHelper helper = new BasketCombinedItemHelper();
        return helper.getPrice(this);
    }
}
