//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Category.java
//  @ Date : 1/21/2012
//  @ Author : 
//
//
package com.sefryek.doublepizza.model;

import com.sefryek.doublepizza.InMemoryData;
import org.apache.struts.Globals;

import java.io.Serializable;
import java.util.List;
import java.util.Locale;

public class Category implements Comparable, Serializable {

    private String id; // webCategory:catId id;
    private String nameKey;
    private String descriptionKey;
    private int sequence; // sequence
    private String imageURL;
    private List<SubCategory> subCategoryList;
    private Boolean isRedeemable = false;


    public Category(String id, String nameKey, String descriptionKey, int sequence, String imageURL,  Boolean isRedeemable) {

        this.id = id;
        this.nameKey = nameKey;
        this.descriptionKey = descriptionKey;
        this.sequence = sequence;
        this.imageURL = imageURL;
        this.isRedeemable = isRedeemable == null ? false : isRedeemable;

    }

    public Boolean getIsRedeemable() {
        return isRedeemable;
    }

    public void setIsRedeemable(Boolean isRedeemable) {
        this.isRedeemable = isRedeemable;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName(Locale loc) {
        return InMemoryData.getData(nameKey, loc);

    }

    public String getDescription(Locale loc) {
        return InMemoryData.getData(descriptionKey, loc);

    }

    public int getSequence() {
        return sequence;
    }

    public void setSequence(int sequence) {
        this.sequence = sequence;
    }

    public String getImageURL() {
        return imageURL;
    }

    public void setImageURL(String imageURL) {
        this.imageURL = imageURL;
    }

    public List<SubCategory> getSubCategoryList() {
        return subCategoryList;
    }

    public void setSubCategoryList(List<SubCategory> subCategoryList) {
        this.subCategoryList = subCategoryList;
    }

    public int compareTo(Object object) {

        Category that = (Category) object;
        Integer thisSequence = this.getSequence();
        Integer thatSequence = that.getSequence();

        if (thisSequence > thatSequence) {
            return 1;
        } else if (thisSequence < thatSequence) {
            return -1;
        } else {
            return 0;
        }

    }
}
