package com.sefryek.doublepizza.model;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Basket.java
//  @ Date : 1/12/2012
//  @ Author : 
//
//


import com.sefryek.common.MessageUtil;
import com.sefryek.doublepizza.core.Constant;
import com.sefryek.doublepizza.device.ServicesConstant;

import javax.persistence.*;
import javax.persistence.Table;
import javax.servlet.http.HttpServletRequest;

@Entity
@Table(name =Constant.FEEDBACK_TBL_NAME)
public class FeedBack {

    public enum Type {WEB, iPhone, Others}

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;

    @Column (name = Constant.FEEDBACK_NAME)
    private String name;

    @Column (name = Constant.FEEDBACK_EMAIL)
    private String email;

    @Column (name = Constant.FEEDBACK_MESSAGE)
    private String message;

    @Column (name = Constant.FEEDBACK_SOURCE)
    private Type source;

    @Column (name = Constant.FEEDBACK_STORENUMBER)
    private String storeNumber;

    @Column (name = Constant.FEEDBACK_MILLISECONDS)
    private String milliSeconds;

    @Column (name = "Version")
    private String version;

    public FeedBack(String version, String name, String email, String message, Type source, String storeNumber, String milliSeconds)
    {
        this.version = version;
        this.name=name;
        this.email=email;
        this.message=message;
        this.source=source;
        this.storeNumber=storeNumber;
        this.milliSeconds=milliSeconds;
    }

    public FeedBack() {

    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Type getSource() {
        return source;
    }

    public void setSource(Type source) {
        this.source = source;
    }

    public String getStoreNumber() {
        return storeNumber;
    }

    public void setStoreNumber(String storeNumber) {
        this.storeNumber = storeNumber;
    }

    public String getMilliSeconds() {
        return milliSeconds;
    }

    public void setMilliSeconds(String milliSeconds) {
        this.milliSeconds = milliSeconds;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String validateData( HttpServletRequest request ){
        String message = null;
        if( email.length() > ServicesConstant.THRESHOLD_MAIL_MAX_LEN ){
            message = MessageUtil.get("message.error.email.threshold", request.getLocale() );
        }

        if( storeNumber != null && storeNumber.length() > ServicesConstant.THRESHOLD_STORE_MAX_LEN ){
            if( message == null )
                message ="";
            else
                message+="\n";

            message += MessageUtil.get("message.error.storeId.threshold", request.getLocale() );
            
        }

        return message;
    }


}