//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Menu.java
//  @ Date : 1/21/2012
//  @ Author :Sepehr 
//
//
package com.sefryek.doublepizza.model;

import java.io.Serializable;
import java.util.List;

public class Menu implements Serializable, Cloneable {

    public Menu(String name) {
        this.name = name;
    }

    private String name;

    private List<Category> categoryList;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Category> getCategoryList() {
        return categoryList;
    }

    public void setCategoryList(List<Category> categoryList) {
        this.categoryList = categoryList;
    }

    @Override
    public Object clone(){
        try {
            return super.clone();
        } catch (CloneNotSupportedException e) {
            e.printStackTrace();
            return null;
        }

    }

}
