package com.sefryek.doublepizza.model;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SubOrder.java
//  @ Date : 1/12/2012
//  @ Author : 
//
//


import java.io.Serializable;

public class SubOrder implements Serializable {
	private Integer id;
	private Class classType;
	private MenuSingleItem item;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Class getClassType() {
        return classType;
    }

    public void setClassType(Class classType) {
        this.classType = classType;
    }

    public MenuSingleItem getItem() {
        return item;
    }

    public void setItem(MenuSingleItem item) {
        this.item = item;
    }
}
