package com.sefryek.doublepizza.model;

import java.io.Serializable;
import java.util.List;
import java.util.Map;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Topping.java
//  @ Date : 1/12/2012
//  @ Author : 
//
//

public class Table implements Serializable {

    private List<Map<String,List<Object>>> columnHeader;
    private String name;

    public List<Map<String, List<Object>>> getColumnHeader() {
        return columnHeader;
    }

    public void setColumnHeader(List<Map<String, List<Object>>> columnHeader) {
        this.columnHeader = columnHeader;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}