package com.sefryek.doublepizza.model;

import java.io.Serializable;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ToppingSubCategory.java
//  @ Date : 1/12/2012
//  @ Author : 
//
//


public class ToppingSubCategory implements Serializable {

    private Class classType;
    private Object object;

    public ToppingSubCategory(Class type,Object object) {
        this.classType=type;
        this.object=object;
    }

    public Class getClassType() {
        return classType;
    }

    public void setClassType(Class classType) {
        this.classType = classType;
    }

    public Object getObject() {
        return object;
    }

    public void setObject(Object object) {
        this.object = object;
    }
}
