package com.sefryek.doublepizza.model;

import com.sefryek.doublepizza.InMemoryData;

import java.io.Serializable;
import java.util.List;
import java.util.Locale;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ToppingCategory.java
//  @ Date : 1/12/2012
//  @ Author : 
//
//

public class ToppingCategory implements Serializable {

    private Integer id;
    private String nameKey;
    private List<ToppingSubCategory> toppingSubCategoryList;
    private Integer[][] toppingConflictArray;
    private List<Integer> defaultToppingList;
    private Boolean exclusive;

    public Boolean getExclusive() {
        return exclusive;
    }

    public void setExclusive(Boolean exclusive) {
        this.exclusive = exclusive;
    }

    public ToppingCategory(Integer id, String nameKey, Boolean exclusive) {

        this.id = id;
        this.nameKey = nameKey;
        this.exclusive = exclusive;

    }

    public ToppingCategory() {
    }


    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

     public String getName(Locale loc) {
        return InMemoryData.getData(nameKey, loc);

    }

    public String getNameKey() {
        return nameKey;
    }


    public void setNameKey(String nameKey) {
        this.nameKey = nameKey;

    }

    public List<ToppingSubCategory> getToppingSubCategoryList() {
        return toppingSubCategoryList;
    }

    public void setToppingSubCategoryList(List<ToppingSubCategory> toppingSubCategoryList) {
        this.toppingSubCategoryList = toppingSubCategoryList;
    }

    public Integer[][] getToppingConflictArray() {
        return toppingConflictArray;
    }

    public void setToppingConflictArray(Integer[][] toppingConflictArray) {
        this.toppingConflictArray = toppingConflictArray;
    }

    public List<Integer> getDefaultToppingList() {
        return defaultToppingList;
    }

    public void setDefaultToppingList(List<Integer> defaultToppingList) {
        this.defaultToppingList = defaultToppingList;
    }
}
