package com.sefryek.doublepizza.model;

import com.sefryek.doublepizza.InMemoryData;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Locale;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Topping.java
//  @ Date : 1/12/2012
//  @ Author : 
//
//


public class Topping implements Serializable {
    private Integer id;
    private BigDecimal price;
    private String nameKey;
    private Integer webSequence;
    

    public Topping(Integer id, BigDecimal price, String nameKey, Integer webSequence) {
        this.id = id;
        this.price = price;
        this.nameKey = nameKey;
        this.webSequence = webSequence;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }


    public String getName(Locale loc) {
        return InMemoryData.getData(nameKey, loc);

    }

    public Integer getWebSequence() {
        return webSequence;
    }

    public void setWebSequence(Integer webSequence) {
        this.webSequence = webSequence;
    }

    public int compareTo(Object object) {
        Topping that = (Topping) object;
        BigDecimal thisPrice = this.getPrice();
        BigDecimal thatPrice = that.getPrice();
        return thisPrice.compareTo(thatPrice);
    }
}
