package com.sefryek.doublepizza.model;

import java.util.List;
import java.io.Serializable;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ExclusiveTopping.java
//  @ Date : 1/12/2012
//  @ Author : 
//
//



public class ExclusiveTopping implements Serializable {
	private String name;
	private List<Topping> topping;
	private Integer defaultChoice;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Topping> getTopping() {
        return topping;
    }

    public void setTopping(List<Topping> topping) {
        this.topping = topping;
    }

    public Integer getDefaultChoice() {
        return defaultChoice;
    }

    public void setDefaultChoice(Integer defaultChoice) {
        this.defaultChoice = defaultChoice;
    }
}
