//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Menu.java
//  @ Date : 1/21/2012
//  @ Author :Sepehr 
//
//
package com.sefryek.doublepizza.model;

import java.util.List;
import java.io.Serializable;

public class Menu implements Serializable {

    public Menu(String name) {
        this.name = name;
    }

    private String name;

    private List<Category> categoryList;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Category> getCategoryList() {
        return categoryList;
    }

    public void setCategoryList(List<Category> categoryList) {
        this.categoryList = categoryList;
    }

}
